### ISSUE TITLE
mpp好像不支持h264 high10 profile的解码，有办法自动fallback到软解吗

### ISSUE THREAD

**Issue by jjm2473** [JeffyCN/FFmpeg#11]

**Comment by JeffyCN** [comment]
high10 should be supported by a few chips(newer than 3288 i guess).

SW fallback should be enabled by default in FFmpeg(google tells that, for more details please ask FFmpeg upstream).

If that doesn't work, try to check the profile and return error in rkmpp_init_decoder().

**Comment by jjm2473** [comment]
好吧，h264 high10 profile是支持的，只是因为以前的bug，在输出“Decoder noticed an info change”之后就会卡住。
