### ISSUE TITLE
libavcodec/get_buffer.c中的286行，未找到定义

### ISSUE THREAD

**Issue by jiale-gdyd** [JeffyCN/FFmpeg#13]
if (s->codec->caps_internal & FF_CODEC_CAP_CONTIGUOUS_BUFFERS) {
上面这一句应该改为
if (ffcodec(s->codec)->caps_internal & FF_CODEC_CAP_CONTIGUOUS_BUFFERS) {

**Comment by jiale-gdyd** [comment]
还有就是libavcodec/rkmppdec.c的792行的:
        .p.caps_internal  = FF_CODEC_CAP_CONTIGUOUS_BUFFERS, \
应该修改为:
        .caps_internal  = FF_CODEC_CAP_CONTIGUOUS_BUFFERS, \

**Comment by jiale-gdyd** [comment]
libavcodec/codec_internal.h:79:45: warning: unsigned conversion from ‘int’ to ‘unsigned int:29’ changes value from ‘-2147483648’ to ‘0’ [-Woverflow]
 #define FF_CODEC_CAP_CONTIGUOUS_BUFFERS     (1 << 31)
                                             ^
libavcodec/rkmppdec.c:793:27: note: in expansion of macro ‘FF_CODEC_CAP_CONTIGUOUS_BUFFERS’
         .caps_internal  = FF_CODEC_CAP_CONTIGUOUS_BUFFERS, \
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by JeffyCN** [comment]
wait, which branch were you using? i was testing 4.4

**Comment by JeffyCN** [comment]
hmmm, there're something wrong in the 5.1 and master branches, fix it right now!

**Comment by jiale-gdyd** [comment]
还是5.1的分支:
![image](https://user-images.githubusercontent.com/65750284/210776439-8df6dc13-1a72-4805-ae47-ba3b24e7999e.png)
需要在rkmppdec.c中天界缺失的头文件:
![image](https://user-images.githubusercontent.com/65750284/210777058-d8a44347-85e4-4b4f-8297-2bc34d0d0651.png)

**Comment by JeffyCN** [comment]
right, done
