### ISSUE TITLE
rkmppdec 解码异常的问题

### ISSUE THREAD

**Issue by lion117** [JeffyCN/FFmpeg#21]
# 测试背景1
1. 在麒麟aarch64 系统上使用ffmpeg 播放 mp4视频文件
2. ffmpeg版本为4.2.2的版本
3. RK3399

# 异常情况
1. 获取解码后的av_frame_get_best_effort_timestamp 异常为负值.   frame->pts 间歇性的为0. packet->pts完全正常
> 同一份代码, 在ubuntu-x64平台下运行正常. 可正确获得pts. 均无此类情况. 
```
av_frame_get_best_effort_timestamp(&player->vframe);  

```

2.  设置解码器内部禁止缓冲, 输入packet pts和输出vframe的pts 总是间隔一帧. 导致端到端时延增加约40ms
```
player->vcodec_context->delay = 0;          // 禁止内部缓冲
avcodec_decode_video2(player->vcodec_context, &player->vframe, &gotvideo, packet);
```

**Comment by JeffyCN** [comment]
deprecated due to license issue, check gstreamer instead or https://github.com/hbiyik/FFmpeg

**Comment by AbelDengGang** [comment]
Do you mean gstreamer rockchip plug in? Could you give me gstreamer's url?

**Comment by lion117** [comment]
> deprecated due to license issue, check gstreamer instead or https://github.com/hbiyik/FFmpeg

The repository you mentioned (https://github.com/hbiyik/FFmpeg) appears to be a fork of the original FFmpeg repository (https://github.com/FFmpeg/FFmpeg) by hbiyik, who might be a foreign individual (laowai).

Was the repository at https://github.com/hbiyik/FFmpeg maintained specifically for the purpose of optimizing the MPP (Media Processing Platform) adapter?

**Comment by JeffyCN** [comment]
> Do you mean gstreamer rockchip plug in? Could you give me gstreamer's url?
yes, check: https://github.com/JeffyCN/mirrors/tree/gstreamer-rockchip

**Comment by JeffyCN** [comment]
> The repository you mentioned (https://github.com/hbiyik/FFmpeg) appears to be a fork of the original FFmpeg repository (https://github.com/FFmpeg/FFmpeg) by hbiyik, who might be a foreign individual (laowai).

right, there're multiple branches, you can open issues there for more details.

> Was the repository at https://github.com/hbiyik/FFmpeg maintained specifically for the purpose of optimizing the MPP (Media Processing Platform) adapter?

guess so
