### ISSUE TITLE
Increase performance?

### ISSUE THREAD

**Issue by AIhasArrived** [JeffyCN/FFmpeg#22]
Was anyone able to have faster porcessing with FFMPEG? 
I have a bunch of GPU but it is using very little, and it is being VERY SLOW at making a video out of frames I collected.
Any insignt would be appreciated.
thanks

**Comment by JeffyCN** [comment]
1/ it's using VPU hardware module to do the decoding, unlike PC(use GPU)
2/ this code doesn't support mpp encoder. if you need encoder, try to check gstreamer or: https://github.com/nyanmisaka/ffmpeg-rockchip
