### ISSUE TITLE
New FFMpeg Repo

### ISSUE THREAD

**Issue by hbiyik** [JeffyCN/FFmpeg#24]
Hello @JeffyCN 

I have archived the my fork and want to migrate everyone to the new work at https://github.com/nyanmisaka/ffmpeg-rockchip

Would you be kind to update the description in your repo?

![image](https://github.com/JeffyCN/FFmpeg/assets/24766436/eb9277fb-ef8f-4478-811d-a1bf69b425de)

**Comment by JeffyCN** [comment]
sure, i've updated it :)

**Comment by hbiyik** [comment]
super closing.
