### ISSUE TITLE
这个版本的ffmpeg支持硬编和软解吗

### ISSUE THREAD

**Issue by tu-nie** [JeffyCN/FFmpeg#25]

**Comment by JeffyCN** [comment]
sorry, this is no longer supported.

**Comment by tu-nie** [comment]
您好，知不知道哪个版本的ffmpeg支持硬编码和软解码的




范宇俊玉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JeffyCN/FFmpeg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月8日(星期一) 上午9:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JeffyCN/FFmpeg] 这个版本的ffmpeg支持硬编和软解吗 (Issue #25)





 
sorry, this is no longer supported.

**Comment by JeffyCN** [comment]
deprecated due to license issue, check gstreamer instead or https://github.com/nyanmisaka/ffmpeg-rockchip
