### ISSUE TITLE
Decoder can't recover after (Received a errinfo frame)

### ISSUE THREAD

**Issue by AreaScout** [JeffyCN/FFmpeg#5]
When streaming TV Channels with PVR.HTS backend, after unspecified time (sometimes one hour, sometimes 10min) frame stucks, when I stop streaming and start over again I have only a green screen.

It just happens when rkmppdec backend get's here https://github.com/JeffyCN/FFmpeg/blob/master/libavcodec/rkmppdec.c#L468

Here is the kernel/syslog https://pastebin.com/raw/7caH5qPv

Here is the respective KODI log https://pastebin.com/raw/zrFZDvwb

How can I recover from that error without losing link to decoder, or can I do something against it ? (rkvdec2_link_wait_result)

Regards,
Daniel

**Comment by JeffyCN** [comment]
this looks like a mpp issue, not ffmpeg.

maybe the input stream is corrupted due to network.

you can try to dump the input packets while testing, and check the error inputs with mpp's mpi_dec_test to confirm.

for mpp issues, please contact herman.chen@rock-chips.com

**Comment by AreaScout** [comment]
Thank you very much !
